<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AMAZON_completed</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d3ccd419-e575-4723-840f-70d19f164be3</testSuiteGuid>
   <testCaseLink>
      <guid>0849fd97-cd09-4af7-a6df-6e944b8c43b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>4326d370-0103-4fd0-b8ea-6ccd07c21258</id>
         <masked>false</masked>
         <name>item</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/TestCases/TC_001_DDTExcelmode</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ef037ed1-38c0-4afa-b0f3-14ef691f7cb5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DDT/DDT</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ef037ed1-38c0-4afa-b0f3-14ef691f7cb5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>52564f31-7401-4377-9df1-9fb98ff2bde0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ef037ed1-38c0-4afa-b0f3-14ef691f7cb5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>4326d370-0103-4fd0-b8ea-6ccd07c21258</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b76675d6-c5c3-4b80-a05e-f5f8c335989c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/DDT internal data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b41c193e-34ca-4697-a903-d7b5874dd82b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08113b0d-4c26-49c2-ba65-b191e5119b3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c96bfab2-39fc-4805-865d-9692efc06baf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/DDTglobal variable</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>86f1a107-f933-4e08-beca-ef603c9c8b18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/TC_002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9f7ce618-bc0b-4d92-aed3-43121046c2a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/TC_003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>52c21007-71af-4ad0-a0cb-45785842dca9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/TC_004</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>09dcc1ff-7a3d-451e-baa6-6a0c4f2198c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/TC_005</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
