<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__fluid-quad-image-label-v2_style_fluidL_00fc7b</name>
   <tag></tag>
   <elementGuidId>526ec125-6016-4a0a-97bb-de41260cc0b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Headsets']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img._fluid-quad-image-label-v2_style_fluidLandscapeImage__2euAK._fluid-quad-image-label-v2_style_fluidImage__gTBjA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2d5bd0d2-2510-44b3-8d17-813eba9caca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Headsets</value>
      <webElementGuid>7a8b4532-e783-44ac-b2f3-45150af037e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Headset_2x._SY232_CB667159060_.jpg</value>
      <webElementGuid>7414320a-a519-4e0d-805b-d32c44bc0b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_fluid-quad-image-label-v2_style_fluidLandscapeImage__2euAK _fluid-quad-image-label-v2_style_fluidImage__gTBjA</value>
      <webElementGuid>24799308-25c1-462d-a697-e58b5aade2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Headset_2x._SY232_CB667159060_.jpg</value>
      <webElementGuid>493f666c-10ac-4af6-ae71-2e5a5a24fa7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstancef_11Jf1q5D-XtpxqcH8Yuw&quot;)/div[@class=&quot;_fluid-quad-image-label-v2_style_fluidQuadImageLabelBody__3tld0&quot;]/div[@class=&quot;a-section a-spacing-small _fluid-quad-image-label-v2_style_gridRowOne__1t0zL&quot;]/div[@class=&quot;a-section a-spacing-none _fluid-quad-image-label-v2_style_quadrantContainer__3TMqG _fluid-quad-image-label-v2_style_leftQuadrant__21nVp&quot;]/a[@class=&quot;a-link-normal _fluid-quad-image-label-v2_style_centerImage__30wh- aok-block image-window&quot;]/div[@class=&quot;a-section a-spacing-none _fluid-quad-image-label-v2_style_fluidImageContainer__2SOMr&quot;]/img[@class=&quot;_fluid-quad-image-label-v2_style_fluidLandscapeImage__2euAK _fluid-quad-image-label-v2_style_fluidImage__gTBjA&quot;]</value>
      <webElementGuid>df0d4263-be3a-4456-bfac-259132d10404</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstancef_11Jf1q5D-XtpxqcH8Yuw']/div[2]/div/div/a/div/img</value>
      <webElementGuid>82ebd91a-1893-4ae3-b3e4-63bff90db81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Headsets']</value>
      <webElementGuid>0900fb40-481b-4974-b14f-39be7fb655b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/div/img</value>
      <webElementGuid>5a31e732-2c7d-4a6a-804e-c772ebe22811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Headsets' and @src = 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Headset_2x._SY232_CB667159060_.jpg']</value>
      <webElementGuid>67c75ecb-ec70-43d7-9261-3448e8f90c07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
