<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_United States</name>
   <tag></tag>
   <elementGuidId>6ed24f4d-d37c-42bd-95be-d890526552a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='icp-touch-link-country']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icp-touch-link-country > span.icp-color-base</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7fe903e4-3531-438c-8594-c418db584a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icp-color-base</value>
      <webElementGuid>0c995f57-448b-4fc4-8559-a6b866559325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>United States</value>
      <webElementGuid>a9719e39-9154-464e-a23e-bc419b9777dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icp-touch-link-country&quot;)/span[@class=&quot;icp-color-base&quot;]</value>
      <webElementGuid>9aa2113c-f64e-44e8-9e59-4a8430ed14c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='icp-touch-link-country']/span[2]</value>
      <webElementGuid>a6e60135-fc4a-4c23-bb44-07f6a3582976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/a[3]/span[2]</value>
      <webElementGuid>1b56284f-3695-49a4-a5f2-8efad099eab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'United States' or . = 'United States')]</value>
      <webElementGuid>b1e0bc36-a1bb-423d-b4fe-243db68152ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
